### ISSUE TITLE
Does not work on 64 bit

### ISSUE THREAD

**Issue by ajfclark** [quekky/AdvancedCameraSettings_r3#2]
Reading Issue #1 I managed to compile, however the program does not run:

```
C:\Users\aclark\Desktop\AdvancedCameraSettings_r3-master\src>java -cp .;dsj.jar
AdvancedCameraSettingsMain
java.lang.UnsatisfiedLinkError: C:\Users\aclark\Desktop\AdvancedCameraSettings_r
3-master\src\dsj.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform, Make s
ure the dsj.dll is on the library path & DirectX9 and WindowsMediaPlayer 9 or gr
eater are installed
Exception in thread "main" java.lang.UnsatisfiedLinkError: de.humatic.dsj.DSFilt
ergraph.initMethodIDs()V
        at de.humatic.dsj.DSFiltergraph.initMethodIDs(Native Method)
        at de.humatic.dsj.DSFiltergraph.<clinit>(SourceFile:144)
        at util.DirectShowCamera.getCameras(DirectShowCamera.java:33)
        at AdvancedCameraSettingsMain.queryCameras(AdvancedCameraSettingsMain.ja
va:31)
        at AdvancedCameraSettingsMain.main(AdvancedCameraSettingsMain.java:21)

C:\Users\aclark\Desktop\AdvancedCameraSettings_r3-master\src>

C:\Users\aclark\Desktop\AdvancedCameraSettings_r3-master\src>java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by ajfclark** [comment]
After downloading the 64 bit version from https://www.humatic.de/htools/dsj.htm I can now start the application. This should be in the readme, as should the compilation instructions.

**Comment by quekky** [comment]
the dll provided is 32bit, so you'll need 32bit java. glad to know that you solved it


The codes are copied from the forum link (the dropbox link was already dead long ago), I'm just helping to host the files here. Since then, I'm not working on any webcam projects anymore, so I'll not be able to help on this. Maybe you want to take over the project, and fork a copy to your github? If you do let me know, I'll put a link to there
